In [2]:
import numpy as np     ## numpy import ediyoruz

In [5]:
a=np.array([1,2,3,4], dtype=float )  ## numpy dizi/liste(array) tanımlıyoruz
b=np.array([1,2,3,4])
print(a*b)             ## array ile direk 4 işlem yapabiliyoruz

[ 1.  4.  9. 16.]


In [8]:
a.shape                ## arrayin boyutlarını gösterir

(4,)

In [9]:
a.reshape(2,2)         ## arrayin boyutlarını değiştirir.

array([[1., 2.],
       [3., 4.]])

In [12]:
a.reshape(-1,2)        ## -1 satır veya sütün sayısını serbest bırakıyor

array([[1., 2.],
       [3., 4.]])

In [19]:
b=list(range(30))
c=np.array(b,ndmin=4)  ## 4 boyutlu bir array dizi oluşturur. 4 kare kutucuk olması 4 boyutlu olduğunu gösterir
c

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]]]])

In [20]:
c.shape

(1, 1, 1, 30)

In [25]:
x=np.array([1,2,3.])
x

array([1., 2., 3.])

In [26]:
x.dtype              ## data type ni verir

dtype('float64')

In [28]:
x.astype("int")      ## data type ni değiştirir

array([1, 2, 3])

In [30]:
np.resize(x,(2,3))

array([[1., 2., 3.],
       [1., 2., 3.]])

In [31]:
np.arange(0,20,2)     ## belirtilen değerler arasında belirtilen sayıda eşit aralıklarla bir dizi oluşturur.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [32]:
np.linspace(0,20,10)  ## belirtilen aralıkta belirtilen sayı kadar eşit aralıklarla bir dizi oluşturur.

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [34]:
np.zeros([3,3])       ## belirtilen boyutlarda 0 değerli bir matris oluşturur 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
np.zeros_like(x)      ## belirtilen bir nesneyi 0 değerleri ile doldurur.

array([0., 0., 0.])

In [36]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [42]:
np.full((2,2),10)

array([[10, 10],
       [10, 10]])

In [47]:
np.random.rand(3,3)       ## 0 ile bir arasında belirtilen boyutlarda eşit aralıklarla matris oluşturur

array([[0.79291533, 0.65618764, 0.22191437],
       [0.57831722, 0.51795075, 0.48011564],
       [0.58533243, 0.84869943, 0.21268084]])

In [48]:
np.random.randn(3,3)     ## ortalama değeri 0 ve standart sapması 1 olan normal dağılıma sahip rastgele sayılar üretir

array([[-1.43778679,  0.3130858 , -0.6057911 ],
       [ 0.59961667, -0.92318071,  0.5829053 ],
       [-0.57109929,  0.12117769, -0.19186353]])

In [50]:
z=np.random.randint(1,100,10)  ## belirtilen aralıkta belirtilen değerde rasgele sayılar üretir
z

array([36, 78, 84, 31, 61,  8, 50,  6, 22,  9])

In [52]:
z.max()         ## max,min dizinin max ve min değerlerini gösterir

84

In [53]:
z.argmax()     ## argmax,argmin dizinin max ve min değerlerinin indeksini gösterir

2

In [54]:
z.ndim         ## boyut sayısını verir.

1

In [55]:
z.size         ## Bir dizideki toplam eleman sayısı

10

In [56]:
z.itemsize     ## her bir elemanının bellekte kaç byte kapladığını gösterir.

4

In [61]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
a.transpose()    ## Bir matrisin transpozunu almak, matrisin satırlarını sütunlarına, sütunlarını da satırlarına dönüştürür.

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
x = np.array([1,2,3])
y = np.array([4,5,6])
xy = np.concatenate((x, y))       ## x ve y matrislerini birleştiriyor.
xy                                ## axis=0 parametresi, dizilerin satır bazında (dikey birleştirme) birleştirilmesini, 
                                  ## axis=1 parametresi ise sütun bazında (yatay birleştirme) birleştirilmesini sağlar.

array([1, 2, 3, 4, 5, 6])

In [65]:
a = np.array([1,2,3,4,5,6,7,8])
np.split(a, 4)                    ## numpy dizisini belirtilen eksende eşit parçalara böler

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [66]:
x = np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [67]:
np.split(x, [1,3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [68]:
a = np.array([2,1,4,3,5])
np.sort(a, axis=-1)         ## numeric veya alfabetik sıralama yapar

array([1, 2, 3, 4, 5])

In [70]:
a.sort()
a

array([1, 2, 3, 4, 5])

In [72]:
myarr = np.random.randint(5,100,(3,3))
myarr

array([[80, 37, 23],
       [58, 24, 48],
       [47, 98, 68]])

In [73]:
np.sort(myarr, axis=0)        ## eksene göre sıralama yapar

array([[47, 24, 23],
       [58, 37, 48],
       [80, 98, 68]])

In [74]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [75]:
arr[-1]          ## -1 sonuncu elemeandır.sondan başa -1,-2...

23

In [76]:
arr[1::2]        ##  2 şer atlayarak 1.indeksten sonuna kadar gider

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [77]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
arr_2d[1]

array([4, 5, 6])

In [79]:
arr_2d[1][2]

6

In [80]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [82]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [83]:
[a[1], a[3], a[5]]  

[3, 9, 15]

In [84]:
index_list = [1,3,5]      ## index listesi index numarası karşılığına gelen değerler döndürür
a[index_list]

array([ 3,  9, 15])

In [85]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
arr[[2,4,6,8]]     ## sadece indekse karşılık gelen satırları alır

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [87]:
arr[[0,2,3],[0,1,3]]       ## satır ve sütun indekslerinin kesiştiği değeri alır

array([ 0, 21, 33])

In [88]:
myarr =np.random.randint(1,50,5)
myarr

array([ 4, 10, 30, 47, 16])

In [91]:
arr = np.arange(1,11)

In [95]:
bool_arr = arr > 4     ## 4 ten büyük değerleri true dondürür
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [93]:
arr[bool_arr]        ## 4 ten büyük değerlere sahip indekslerin değerlerini verir.

array([ 5,  6,  7,  8,  9, 10])

In [96]:
arr[(arr !=3) & (arr !=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])